version: '3.9'

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autorizador_procedimentos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wildfly-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net: